apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: pvci-test
spec:
  selector:
    app: minio
  ports:
    - name: http-web
      protocol: "TCP"
      port: 9000
      targetPort: http-web
  type: ClusterIP
