apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-rwo
  namespace: pvci-test
spec:
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "60Mi"