apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-pcv
  namespace: pvci-test
spec:
  dataSource:
    kind: PersistentVolumeClaim
    name: test-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: "60Mi"
  storageClassName: rook-ceph-block
  volumeMode: Filesystem